/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const handle: typeof import('./src/hooks.server')['handle']
  const i: typeof import('@inlang/sdk-js')['i']
  const inlang: typeof import('@inlang/sdk-js')['inlang']
}
