version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: '111-some-random-value'
      SECRET: '333-some-random-value'
      ADMIN_EMAIL: 'jm51@bk.ru'
      ADMIN_PASSWORD: '74$PV@3sTJ$wz!awA&w2'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: true
